run:
  timeout: 5m
  tests: true

linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15

  goconst:

    min-len: 3
    min-occurences: 3
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
  
linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck
    - gocyclo
    - gocritic
    - revive

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - linters:
        - revive
      text: "exported (method|function|type|const|var) (.+) should have comment or be unexported"

